### ISSUE TITLE
(v0.9.0) (Bug) - complie error when build stack

### ISSUE THREAD

**Issue by PanupongDeve** [thaitype/kubricate#35]
I create stack and try to build in kubricate v0.9.0 but I get some Error. Please Help me?

```
src/FileShareStack/FileShareStack.ts:5:14 - error TS4094: Property '_composer' of exported anonymous class type may not be private or protected.

5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
               ~~~~~~~~~~~~~~

  src/FileShareStack/FileShareStack.ts:5:14
    5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
                   ~~~~~~~~~~~~~~
    Add a type annotation to the variable FileShareStack.

src/FileShareStack/FileShareStack.ts:5:14 - error TS4094: Property '_defaultSecretManagerId' of exported anonymous class type may not be private or protected.

5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
               ~~~~~~~~~~~~~~

  src/FileShareStack/FileShareStack.ts:5:14
    5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
                   ~~~~~~~~~~~~~~
    Add a type annotation to the variable FileShareStack.

src/FileShareStack/FileShareStack.ts:5:14 - error TS4094: Property '_secretManagers' of exported anonymous class type may not be private or protected.

5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
               ~~~~~~~~~~~~~~

  src/FileShareStack/FileShareStack.ts:5:14
    5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
                   ~~~~~~~~~~~~~~
    Add a type annotation to the variable FileShareStack.

src/FileShareStack/FileShareStack.ts:5:14 - error TS4094: Property '_targetInjects' of exported anonymous class type may not be private or protected.

5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
               ~~~~~~~~~~~~~~

  src/FileShareStack/FileShareStack.ts:5:14
    5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
                   ~~~~~~~~~~~~~~
    Add a type annotation to the variable FileShareStack.

src/FileShareStack/FileShareStack.ts:5:14 - error TS4094: Property 'builder' of exported anonymous class type may not be private or protected.

5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
               ~~~~~~~~~~~~~~

  src/FileShareStack/FileShareStack.ts:5:14
    5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
                   ~~~~~~~~~~~~~~
    Add a type annotation to the variable FileShareStack.

src/FileShareStack/FileShareStack.ts:5:14 - error TS4094: Property 'setComposer' of exported anonymous class type may not be private or protected.

5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
               ~~~~~~~~~~~~~~

  src/FileShareStack/FileShareStack.ts:5:14
    5 export const FileShareStack = createStack('FileShareStack', (data: IFileShareStack) => {
                   ~~~~~~~~~~~~~~
    Add a type annotation to the variable FileShareStack.


Found 6 errors.

error: script "build-esm" exited with code 1
error: script "build" exited with code 1
```
